/**
 * Capture real screenshots of the running WebApp for the public README.
 *
 * Requires a RUNNING backend (http://127.0.0.1:8000) and frontend
 * (default http://localhost:5173) - start them with START.bat first.
 *
 * Every screenshot comes from the real application: a throwaway demo account is
 * registered, images are uploaded through the real UI and the real trained model
 * produces the results. No mock-ups, no design comps, no fabricated predictions.
 *
 * Which images are uploaded is configurable:
 *   --demo-dir <dir>  synthetic demo images generated by scripts/make_demo_images.py
 *                     (default; avoids republishing third-party lesion photos)
 *   --manifest <csv>  fall back to real images from a split manifest
 *
 * Usage (from the repository root):
 *   node scripts/capture_screenshots.mjs [--base-url http://localhost:5173] [--out docs/assets/screenshots]
 */

import { chromium } from '../frontend/node_modules/playwright/index.mjs';
import { mkdir, writeFile, readFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const args = process.argv.slice(2);
function argValue(name, fallback) {
  const index = args.indexOf(name);
  return index !== -1 && args[index + 1] ? args[index + 1] : fallback;
}

const BASE_URL = argValue('--base-url', 'http://localhost:5173');
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.resolve(REPO_ROOT, argValue('--out', 'docs/assets/screenshots'));
const MANIFEST = path.resolve(REPO_ROOT, argValue('--manifest', 'data/manifests/test.csv'));
const DEMO_DIR = path.resolve(REPO_ROOT, argValue('--demo-dir', 'docs/assets/demo'));

const stamp = Date.now();
const DEMO = {
  email: `demo${stamp}@example.com`,
  username: `demo${stamp}`,
  fullName: '演示账号',
  password: 'Demo!Pass2026',
};

/**
 * Real test-split images used when no synthetic demo directory is available.
 *
 * 116.jpg / 1073.jpg are predicted benign, 106.jpg is predicted malignant - the
 * probabilities were measured on the live API before this script was finalised, so
 * the screenshots show a real probability spread instead of a saturated case.
 * The measurements themselves are recorded in screenshots.json.
 */
const DEMO_IMAGES = ['116.jpg', '106.jpg', '1073.jpg'];

async function pickFromDemoDir() {
  if (!existsSync(DEMO_DIR)) return [];
  const names = (await readdir(DEMO_DIR))
    .filter((name) => /\.(jpe?g|png|webp|bmp)$/i.test(name))
    .sort();
  return names.slice(0, 3).map((name) => ({
    path: path.join(DEMO_DIR, name),
    label: 'synthetic-demo',
    filename: name,
  }));
}

async function pickFromManifest() {
  const content = await readFile(MANIFEST, 'utf8');
  const rows = content
    .trim()
    .split(/\r?\n/)
    .slice(1)
    .map((line) => {
      const parts = line.split(',');
      return { path: parts[0], label: parts[3], filename: path.basename(parts[0]) };
    });
  const chosen = [];
  for (const name of DEMO_IMAGES) {
    const row = rows.find((item) => item.filename === name);
    if (row && existsSync(row.path)) chosen.push(row);
    else console.warn(`[warn] demo image not found in manifest: ${name}`);
  }
  return chosen;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  let images = await pickFromDemoDir();
  let imageSource = 'synthetic demo images (scripts/make_demo_images.py)';
  if (images.length < 2) {
    images = await pickFromManifest();
    imageSource = `split manifest (${path.relative(REPO_ROOT, MANIFEST).replace(/\\/g, '/')})`;
  }
  if (images.length < 2) {
    throw new Error(`need at least 2 demo images, found ${images.length}`);
  }
  console.log(`[info] uploading ${images.length} image(s) from ${imageSource}`);

  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: { width: 1440, height: 900 },
    deviceScaleFactor: 1.5,
    locale: 'zh-CN',
    timezoneId: 'Asia/Shanghai',
    reducedMotion: 'reduce',
  });
  const page = await context.newPage();
  page.setDefaultTimeout(30_000);

  const captured = [];
  const results = [];

  async function shot(name, options = {}) {
    const file = path.join(OUT_DIR, name);
    await page.screenshot({ path: file, fullPage: options.fullPage ?? false });
    captured.push(name);
    console.log(`[shot] ${name}`);
  }

  async function goto(pathname) {
    await page.goto(`${BASE_URL}${pathname}`, { waitUntil: 'networkidle' });
  }

  // ---------------------------------------------------------------- public pages
  await goto('/');
  await page.waitForSelector('h1');
  await shot('01_home.png', { fullPage: true });
  // Above-the-fold shot used as the README hero image: the full-page capture is
  // too tall to stay readable when GitHub scales it down.
  await shot('00_home_hero.png');

  await goto('/login');
  await page.waitForSelector('[data-testid="login-submit"]');
  await shot('02_login.png');

  await goto('/register');
  await page.waitForSelector('[data-testid="register-submit"]');
  await shot('03_register.png');

  // ---------------------------------------------------------------- register demo account
  await page.fill('[data-testid="register-email"]', DEMO.email);
  await page.fill('[data-testid="register-username"]', DEMO.username);
  await page.fill('#full_name', DEMO.fullName);
  await page.fill('[data-testid="register-password"]', DEMO.password);
  await page.fill('[data-testid="register-confirm"]', DEMO.password);
  await page.click('[data-testid="register-submit"]');
  await page.waitForURL('**/detect', { timeout: 30_000 });
  await page.waitForSelector('[data-testid="dropzone"]');
  await shot('04_detect_empty.png');

  // ---------------------------------------------------------------- real detections
  for (const [index, image] of images.entries()) {
    if (index > 0) {
      await goto('/detect');
      await page.waitForSelector('[data-testid="dropzone"]');
    }
    await page.setInputFiles('input[type="file"]', image.path);
    await page.waitForSelector('[data-testid="preview-image"]');
    if (index === 0) await shot('05_detect_preview.png');

    await page.click('[data-testid="detect-button"]');
    await page.waitForSelector('[data-testid="result-card"]', { timeout: 60_000 });
    await page.waitForSelector('[data-testid="probability-bars"]', { timeout: 30_000 });

    async function text(testId, fallback = '') {
      const handle = await page.$(`[data-testid="${testId}"]`);
      if (!handle) return fallback;
      return ((await handle.textContent()) ?? fallback).trim();
    }

    const cardText = (await page.textContent('[data-testid="result-card"]')) ?? '';
    const record = {
      sourceImage: path.basename(image.path),
      datasetLabel: image.label,
      resultCardText: cardText.replace(/\s+/g, ' ').slice(0, 400),
      confidence: await text('confidence'),
      modelVersion: await text('model-version'),
      advice: await text('advice'),
    };
    results.push(record);
    console.log('[detect]', JSON.stringify(record));

    if (index === 0) await shot('06_detect_result.png', { fullPage: true });
  }

  // ---------------------------------------------------------------- history + detail + compare
  await goto('/history');
  await page.waitForSelector('[data-testid="history-item"]');
  await shot('07_history.png', { fullPage: true });

  const detailLinks = await page.$$('[data-testid="history-item"] a');
  if (detailLinks.length >= 1) {
    await detailLinks[0].click();
    await page.waitForSelector('[data-testid="history-detail"], img', { timeout: 30_000 });
    await page.waitForTimeout(1500); // let the decrypted history image load
    await shot('08_history_detail.png', { fullPage: true });
  } else {
    console.warn('[warn] no history detail link found');
  }

  await goto('/history');
  await page.waitForSelector('[data-testid="history-item"]');
  const checkboxes = await page.$$('[data-testid^="select-detection-"]');
  if (checkboxes.length >= 2) {
    await checkboxes[0].check();
    await checkboxes[1].check();
    await page.click('[data-testid="compare-selected-button"]');
    await page.waitForSelector('[data-testid^="compare-panel-"]', { timeout: 30_000 });
    await page.waitForTimeout(1500);
    await shot('09_compare.png', { fullPage: true });
  } else {
    console.warn(`[warn] need 2 history rows for compare, found ${checkboxes.length}`);
  }

  // ---------------------------------------------------------------- profile + about
  await goto('/profile');
  await page.waitForSelector('h1');
  await shot('10_profile.png');

  await goto('/about');
  await page.waitForSelector('h1');
  await shot('11_about.png', { fullPage: true });

  // ---------------------------------------------------------------- model evaluation page
  await goto('/evaluation');
  await page.waitForSelector('[data-testid="evaluation-page"]');
  await page.waitForTimeout(800); // let the static plots load
  await shot('12_evaluation.png', { fullPage: true });

  await browser.close();

  const meta = {
    capturedAt: new Date().toISOString(),
    baseUrl: BASE_URL,
    viewport: '1440x900 @1.5x',
    imageSource,
    uploadedImages: images.map((image) => image.filename),
    demoAccount: {
      // the throwaway account is deleted by the server between runs; the local
      // part of the address is kept so the naming scheme stays reproducible
      usernamePattern: 'demo<timestamp>',
      fullName: DEMO.fullName,
    },
    screenshots: captured,
    detections: results,
  };
  await writeFile(path.join(OUT_DIR, 'screenshots.json'), JSON.stringify(meta, null, 2), 'utf8');
  console.log(`[done] ${captured.length} screenshots -> ${OUT_DIR}`);
}

main()
  .then(() => {
    process.exit(0);
  })
  .catch(async (error) => {
    console.error('[FAIL]', error);
    process.exit(1);
  });
