"""Generate the two secrets the app needs and print them as .env lines.

Usage
-----
python scripts/generate_secrets.py >> .env

The values are printed to stdout only; nothing is written to disk by this
script and nothing is committed to the repository.
"""

from __future__ import annotations

import secrets

from cryptography.fernet import Fernet


def main() -> int:
    print("# Generated by scripts/generate_secrets.py — keep this file private")
    print(f"SESSION_SECRET={secrets.token_urlsafe(48)}")
    print(f"IMAGE_ENCRYPTION_KEY={Fernet.generate_key().decode()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
